### ISSUE TITLE
USER STORY: Providing and submitting opinion

### ISSUE THREAD

**Issue by Emmacharleswilson** [Emmacharleswilson/My-First-Agile-Project#3]
In order to **provide my opinion on a certain running topic/event** as a **user**, I can **select and submit an answer from the poll**

## Acceptance Criteria:

- user has set running topics and event poll's to pick from 
- user can only select one poll at a time

## Tasks

- [ ] Update View: to include selection buttons and input field for user response
- [ ] Update website view to make running topics and events clear to user
- [ ] Update control functions
- [ ] Create Javascript function to stop users selecting more than one poll at a time
- [ ] Test functionality
