### ISSUE TITLE
USER STORY: Collect and Publish feedback

### ISSUE THREAD

**Issue by Emmacharleswilson** [Emmacharleswilson/My-First-Agile-Project#4]
In order to **collect users feedback** as an **administrator**, I can **publish a poll**

## Acceptance Criteria:

- Administrator can publish up to 5 polls at one time 
- Poll's are only available for one week 

## Tasks

- [ ] Update functionality so that the administrator receives all users feedback
- [ ] Update control function for easy poll publications 
- [ ] Create a Javascript function to cap amount of polls published at maximum 5 polls a week 
- [ ] Create Javascript function to display polls for a week
- [ ] Update website view to : "Poll nearly finished" 
- [ ] Test functionality
